version: '2'
services:
  sce_led_sign:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - '10000:7000'
    volumes:
      - ./static:/app/templates
      - ./server.py:/app/server.py
      - ./sign_message.py:/app/sign_message.py
