version: '2'
services:
  sce_led_sign:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '10000:10000'
    volumes:
      - ./static:/app/static
      - ./server.py:/app/server.py
