version: '2'
services:
  sce_led_sign:
    container_name: sce_led_sign
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ~/.ssh/known_hosts:/app/ssh/known_hosts
      - ~/.ssh/id_rsa:/app/ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/app/ssh/id_rsa.pub
    ports:
      - '80:80'
    tty: true
    privileged: true
  cadvisor:
    image: zcube/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    devices:
      - /dev/kmsg:/dev/kmsg
    depends_on:
      - sce_led_sign
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./monitoring/prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
     - '9090:9090'